services:
  postgres:
    image: postgres:16
    container_name: conectea-postgres
    restart: always
    environment:
      POSTGRES_USER: conectea
      POSTGRES_PASSWORD: conectea
      POSTGRES_DB: conectea
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: